# @author: Yoann Le Crom <yoann.lecrom@gmail.com>
# date:    2017-05-04 09:19:30

#Expose AngularJS views
azimut_frontofficesecurity_backoffice_jsview_main:
    path: /jsviews/main
    defaults:
        _controller: AzimutSecurityBundle:Template:template
        template: 'AzimutFrontofficeSecurityBundle:Backoffice:main.angularjs.twig'
        roles: ['APP_FRONTOFFICE_SECURITY']
        ##Cache template :
        #maxAge: 86400
        #sharedMaxAge: 86400
    options:
        expose: true

azimut_frontofficesecurity_backoffice_jsview_user_list:
    path: /jsviews/user_list
    defaults:
        _controller: AzimutSecurityBundle:Template:template
        template: 'AzimutFrontofficeSecurityBundle:Backoffice:user_list.angularjs.twig'
        roles: ['APP_FRONTOFFICE_SECURITY']
    options:
        expose: true

azimut_frontofficesecurity_backoffice_jsview_user_detail:
    path: /jsviews/user_detail
    defaults:
        _controller: AzimutSecurityBundle:Template:template
        template: 'AzimutFrontofficeSecurityBundle:Backoffice:user_detail.angularjs.twig'
        roles: ['APP_FRONTOFFICE_SECURITY']
    options:
        expose: true

azimut_frontofficesecurity_backoffice_jsview_user_form:
    path: /jsviews/user_form
    defaults: { _controller: AzimutFrontofficeSecurityBundle:Backoffice:userForm }
    options:
        expose: true

azimut_frontofficesecurity_backoffice_jsview_user_update_form:
    path: /jsviews/user_update_form
    defaults: { _controller: AzimutFrontofficeSecurityBundle:Backoffice:userUpdateForm }
    options:
        expose: true

azimut_frontofficesecurity_backoffice_jsview_new_user:
    path: /jsviews/new_user
    defaults:
        _controller: AzimutSecurityBundle:Template:template
        template: 'AzimutFrontofficeSecurityBundle:Backoffice:new_user.angularjs.twig'
        roles: ['APP_FRONTOFFICE_SECURITY']
    options:
        expose: true
