<?php

namespace Azimut\Bundle\MontgolfiereAppBundle\Repository;

/**
 * CampaignSegmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaignSegmentRepository extends \Doctrine\ORM\EntityRepository
{
}
