<?php

namespace Azimut\Bundle\MontgolfiereAppBundle\Repository;

use Azimut\Bundle\MontgolfiereAppBundle\Entity\Campaign;
use Azimut\Bundle\MontgolfiereAppBundle\Entity\CampaignParticipation;
use Azimut\Bundle\MontgolfiereAppBundle\Entity\CampaignSegment;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * CampaignParticipationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaignParticipationRepository extends EntityRepository
{
    public function getFinishedQueryWithAnswers(Campaign $campaign): QueryBuilder
    {
        return $this->createQueryBuilder('cp')
            ->leftJoin('cp.segment', 's')
            ->leftJoin('cp.answers', 'a')
            ->addSelect('a')
            ->where('s.campaign = :campaign')
            ->andWhere('cp.finished = true')
            ->setParameter(':campaign', $campaign)
        ;
    }

}
