<?php

namespace Azimut\Bundle\MontgolfiereAppBundle\Repository;

/**
 * QuestionTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionTagRepository extends \Doctrine\ORM\EntityRepository
{
}
