<?php

namespace Azimut\Bundle\MontgolfiereAppBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * RestitutionItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestitutionItemRepository extends EntityRepository
{

    public function findByThemeAndColor($theme, $firstColor, $secondColor, $thirdColor)
    {
        return $this->createQueryBuilder('r')
            ->where('r.firstColor = :fc')
            ->andWhere('r.secondColor = :sc')
            ->andWhere('r.thirdColor = :tc')
            ->andWhere('r.theme = :theme')
            ->setParameter('fc', $firstColor)
            ->setParameter('sc', $secondColor)
            ->setParameter('tc', $thirdColor)
            ->setParameter('theme', $theme)
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }
}
