# @author: Yoann Le Crom <yoann.lecrom@abstractive.fr>
# date:    2019-02-27 11:00:27

services:
    azimut_demo.basket_subscriber:
        class: Azimut\Bundle\DemoShopExtraBundle\EventListener\BasketSubscriber
        arguments: ['@translator', '@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_subscriber }
