# @author: Yoann Le Crom <yoann.lecrom@gmail.com>
# date:    2017-02-09 14:44:03

azimut_demo_external_app:
    path: /
    defaults: { _controller: AzimutDemoExternalAppBundle:Demo:index }
    options:
        expose: true

azimut_demo_external_app_catch_all:
    path: /{slug}
    requirements: { slug: ".*" }
    defaults: { _controller: AzimutDemoExternalAppBundle:Demo:catchAll }
