# @author: Yoann Le Crom <yoann.lecrom@azimut.net>
# date:   2015-09-24 16:52:45

services:
    azimut_http_kernel_extra.transform_request_listener:
        class: Azimut\Bundle\HttpKernelExtraBundle\Listener\TransformRequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    azimut_http_kernel_extra.detect_localerequest_listener:
        class: Azimut\Bundle\HttpKernelExtraBundle\Listener\DetectLocaleRequestListener
        arguments: ["%locales%", "%locale%"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
